spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    username: postgres
    password: root123
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /logs/online_shop.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR


app:
  jwt:
    access:
      token:
        key: "7476B97341E15983B62DA6505FD71E4B1D9C258FD9F80623"
        expiration-in-ms: 604800000
    refresh:
      token:
        key: "AE291DEBB49897F37D42DE1FE71869B5EF7EB467A6E0BB57"
        expiration-in-ms: 604800000